name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd services/epf-flower-data-science
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd services/epf-flower-data-science
        pytest tests/unit/api/routes